feat(completions): update mise, usage; add fnox

diff --git a/completions/_fnox b/completions/_fnox
--- a/completions/_fnox
+++ b/completions/_fnox
@@ -1,9 +1,9 @@
-#compdef usage
+#compdef fnox
 # @generated by usage-cli from usage spec
 local curcontext="$curcontext"
 
 # caching config
-_usage_usage_cache_policy() {
+_usage_fnox_cache_policy() {
   if [[ -z "${lifetime}" ]]; then
     lifetime=$((60*60*4)) # 4 hours
   fi
@@ -12,19 +12,21 @@ _usage_usage_cache_policy() {
   (( $#oldp ))
 }
 
-_usage() {
+_fnox() {
   typeset -A opt_args
   local curcontext="$curcontext" cache_policy
 
   if ! type -p usage &> /dev/null; then
       echo >&2
-      echo "Error: usage CLI not found. This is required for completions to work in usage." >&2
+      echo "Error: usage CLI not found. This is required for completions to work in fnox." >&2
       echo "See https://usage.jdx.dev for more information." >&2
       return 1
   fi
 
-  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_usage.spec"
-  usage --usage-spec >| "$spec_file"
+  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_fnox_1_19_0.spec"
+  if [[ ! -f "$spec_file" ]]; then
+    fnox usage >| "$spec_file"
+  fi
   local -a completions=()
   while IFS= read -r line; do
     completions+=("$line")
@@ -33,10 +35,10 @@ _usage() {
   return 0
 }
 
-if [ "$funcstack[1]" = "_usage" ]; then
-    _usage "$@"
+if [ "$funcstack[1]" = "_fnox" ]; then
+    _fnox "$@"
 else
-    compdef _usage usage
+    compdef _fnox fnox
 fi
 
 # vim: noet ci pi sts=0 sw=4 ts=4
